### ISSUE TITLE
Roadmap v1.0.0

### ISSUE THREAD

**Issue by leo-desbureaux-tellae** [tellae/bhepop2#40]
- [x] **Merge "qualitative enrichment" feature**: manage analysis for qualitative features, cleanup code, example (https://github.com/tellae/bhepop2/pull/39)
- [x] **Refactoring of enrichment classes**: create a parent class that can be inherited to implement other enrichment methods (e.g uniform) (https://github.com/tellae/bhepop2/issues/17)
- [x] **Improve testing**: add more unit tests, less macro tests. Evaluate macro tests on aggregated results instead of exact comparison with a stored table.
- [x] **Expose analysis methods in enrichment classes** (allows easier calls with class params) (https://github.com/tellae/bhepop2/issues/36) (https://github.com/tellae/bhepop2/issues/19)
- [x] **Create "accessibility" methods**: avoids creating the class, calling `optimize` and `assign_feature_value_to_pop`. Facilitates exterior use. Try to answer the question how do we want to call the bhepop2 library (in Eqasim for instance) (https://github.com/tellae/bhepop2/issues/26)
- [x] **Improve/complete documentation, adapt to qualitative approach**: maybe explain the package on a qualitative example, simpler (https://github.com/tellae/bhepop2/issues/21)
- [x] **Improve example notebooks** (rename with distribution type quantitative/qualitative), make them simpler, lighter
- [ ] Have a **single, smaller synthetic population** for examples and tests. For distributions, we have one real life data set (Filosofi) and a distribution that comes from a population, then used to re-enrich this population. Heavy and realistic VS no distribution data and almost meaningless.

**Comment by leo-desbureaux-tellae** [comment]
Most of these changes are resolved in #42 

Comments:
- More refactoring may be needed (#41)
- Accessibility methods seem less relevant with the new class systems. The double call has been removed, but some more initialisation is needed.
- Documentation still be improved (as always), but some work has been done
- Notebooks have been adapted, but not really improved. They do the work. The qualitative notebook may need a cleanup
- Last point (single, small synthetic population) has not been adressed
