### ISSUE TITLE
Roadmap packaging

### ISSUE THREAD

**Issue by leo-desbureaux-tellae** [tellae/bhepop2#9]
Travaux à effectuer pour la mise à disposition du code sous la forme d'un package :

- [x] Décrire et schématiser l'algorithme principal
- [x] Finaliser le traitement avec la mise en cohérence des résultats et tirage du revenu pour chaque ménage
- [x] Mise au propre du code avec utilisation de classes
- [x] Écrire des fonctions de validation (formats, tests à mi-exécution)
- [x] Tests avec `PyTest`
- [x] Ajout d'une documentation (génération automatique Shpinx)
- [x] Mise en ligne sur ReadTheDocs
- [x] Nommer le package, renommer dossier _src_
- [x] Renommer le repo
- [x] Numéro de version
- [x] License
- [x] Github Actions (tests & code formatting with black)
- [ ] #18 
- [x] Mettre le package sur PiPy (release auto ?)
